### ISSUE TITLE
Neighborhood enrichmen and ligand-receptor interaction calculation based on cell type enrichment 

### ISSUE THREAD

**Issue by moutazhelal** [scverse/squidpy#616]
...
Dear Authors,
Thank you for developing such a tool and thank you for reading my question.

I was trying to calculate Neighborhood enrichment and ligated-receptor interaction on a Visium slide after defining cell abundance using cell2location. I do not have single annotation for each spots like your tutorial explains is their a way to conducted these analysis using cell abundance ?
Thank you very much,
Best,
Moutaz

**Comment by giovp** [comment]
hi @moutazhelal ,

thank you for the interest in Squidpy, so unfortunately for nhood enrichment not, and same for cellphonedb, although for cellphonedb you could still run the tools with some clustering annotation, and then use the cell2location result to filter the cellphonedb results, similar to what it is done in cellphonedb v3. You'd still have to have a clsutering annotation first.

I'd kindly ask you to ask these kinds of questions in https://discourse.scverse.org/ so that other people can contribute to potential analysis ideas. Thanks!
