### ISSUE TITLE
unit of Squidpy spatial co-occurence interval/distance

### ISSUE THREAD

**Issue by cf98** [scverse/squidpy#631]
While calculating spatial co-occurrence following [this tutorial](https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_visium_hne.html) and [this document](https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.co_occurrence.html#squidpy.gr.co_occurrence), I am trying to understand the meaning of the x axis of the plot.
![spatial co-occurrence](https://squidpy.readthedocs.io/en/stable/_images/sphx_glr_tutorial_visium_hne_004.png)

My questions are: what does the distance mean? What's the unit of y axis? Because I am working on visium data, I assume it's not the pixels (hi-res image is 2000x2000 from spaceranger output, and it's way over the number of spots per row or column.

Thanks!
...

**Comment by giovp** [comment]
hi @cf98 sorry thought I replied to this. 

> what does the distance mean? What's the unit of y axis?

the unit is what's is in the title (  p(exp|cluster)/p(exp) ), it's basically the probability of observing a cluster conditioned on another cluster, as increase of the distance to the cluster of interest increase. I would check the paper for details

> it's not the pixels (hi-res image is 2000x2000 from spaceranger output

for the distance, it's not the hires image but the tif image. Does that help?

**Comment by cf98** [comment]
> 

Thank you, that helps!

**Comment by jimmymathews** [comment]
Sorry to continue commenting on this closed issue. I would like to request a little further clarification.
If I understand conditional probability correctly, the y-axis is showing values of the form:

```
P(A and B) / ( P(A) * P(B) )
```

This was confusing at first, because it seemed that the values should be probabilities (between 0 and 1), as insinuated by the term "co-occurrence probability" for these metrics (see docstring). Instead, the correct description seems to be something like "ratio of actual probability of co-occurrence to expected in the case of independence".

Is this understanding correct?
