### ISSUE TITLE
Shift in spatial coordinates

### ISSUE THREAD

**Issue by emir-radkevich** [scverse/squidpy#660]
Hi dev team.

I tried to select a few visium spots in `adata.obsm['spatial']` and ran into problem that do not understand how coordinates are assigned. I thought that the distance between spots should be 100 pixels, though the pattern is different. Based on samples that I had already tested there is some shift that I pictured below.

![image](https://user-images.githubusercontent.com/45240847/224176960-2377bd34-58f9-4535-bef6-7ed41312575b.png)

Could you please explain why this shift is happening? Where can I infer the shift number?
...
Emir.

**Comment by giovp** [comment]
hi @emir-radkevich 

indeed, this issue is really because of the experimental method. The array is not perfect and there are minor differences arising from both physical distances of the array as well as processing artefacts in the pipeline. That's why we use the spatial coordiantes of the centorids directly (in adata.obsm["spatial"]) instead of computing it from such premises.

In short, this is more of a question to spaceranger developers than sdquidpy.

I'm gonna close this, feel free to reopen.
