### ISSUE TITLE
interactive_visualization for stereo-seq 

### ISSUE THREAD

**Issue by lvmt** [scverse/squidpy#674]
Hi, i have a h5ad file (stereo-seq sequencing and analysis by SAW pipeline), but i want 
to explore the data interactive. So, i find squidpy is a nice tools while i cannot use it successfully for my data. 

Can you give me some tips. 

Thanks.
...

**Comment by LLehner** [comment]
Hi @lvmt,

There is no particular reading function for stereo-seq files. Since they basically just consist of coordinates and expression data you can store the coordinates yourself in ```adata.obsm```. A tutorial on how to do this can be found in the squidpy docs [here](https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_read_spatial.html).

**Comment by LLehner** [comment]
Were you able to make use of the data @lvmt?

**Comment by LLehner** [comment]
Hi @lvmt Just as an update, we currently implement a reader for Stereo-seq files, which can then be used with squidpy. It should be available this week.

Also this earlier statement of mine 

> Since they basically just consist of coordinates and expression data you can store the coordinates yourself in adata.obsm.

was clearly wrong. Back then I wasn't fully aware how the Stereo-seq pipeline output actually looks like.

**Comment by lvmt** [comment]
thanks, i'll ahve a try.

**Comment by Zjianglin** [comment]
Hi @lvmt have you solved  this problem?   @LLehner ,  is there any tutorial for analyzing `stereo-seq` spatial transcriptomics data (especially for `multiple samples`)? Thanks.

**Comment by LLehner** [comment]
Hi @Zjianglin, there is a ```stereo-seq``` reader in [spatialdata-io](https://github.com/scverse/spatialdata-io). The reader can already be used, but is not complete and therefore not merged yet. The corresponding PR can be found [here](https://github.com/scverse/spatialdata-io/pull/70). Regarding multiple samples, do you mean bins? In general it shouldn't be an issue since spatialdata can store multiple images and tables etc.

**Comment by LucaMarconato** [comment]
I am actually preparing a short tutorial today, please checked the PR linked by @LLehner.

**Comment by Zjianglin** [comment]
thanks for your reply. I will try it later. Regarding multiple slices/samples, I mean if I have several SRT samples，is there any recommended method/tutorial to integrate them and then analyze together (i.e. removing batch effects, comparative analysis, .etc.), or should I individually analyze one by one? BTW, for stereo-seq data, there are two typical types: square bin (eg. bin50) and cellbin, is there any difference during analysis by squiddy? thanks.

**Comment by LucaMarconato** [comment]
@Zjianglin just a heads up, I have just uploaded the notebook, [you can find the notebook here](https://github.com/scverse/spatialdata-notebooks/blob/main/notebooks/examples/technology_stereoseq.ipynb).

**Comment by LLehner** [comment]
@Zjianglin 

> Regarding multiple slices/samples, I mean if I have several SRT samples，is there any recommended method/tutorial to integrate them and then analyze together (i.e. removing batch effects, comparative analysis, .etc.), or should I individually analyze one by one?

In general it is recommend to apply pre-processing for each slide individually. Regarding the batch effect removal that is a good question, however from what I've heard so far, many people don't apply batch integration for slides. Instead they pre-process each slide individually and the concatenate/merge them. However, I want to emphasize that this is just anecdotal and there is no consensus on whether one should or should not account for batches when analysing many slides. This probably also depends on the data.

> BTW, for stereo-seq data, there are two typical types: square bin (eg. bin50) and cellbin, is there any difference during analysis by squiddy? thanks.

- Yes they differ in their content. The cellbin.gef is the required file for analysis in Squidpy, since it is used to build the table with count matrix and additional information about cells and genes. It's also a required file for the reader.
 
- squarebin.gef contains different aggregations of the data: The larger the bin size, the more cells (and therefore their gene expression) are contained in one observation, so bin50 is already of much lower resolution, since you aggregate cells from a much bigger area than at the lowest bin size. If you read in stereo-seq data then reading the squarebin file is optional. In `stereoseq()` set `read_square_bin=False` to not load it into the spatialdata object.
