### ISSUE TITLE
I cannot get sq.pl.spatial_scatter() to work with my data

### ISSUE THREAD

**Issue by huanlity** [scverse/squidpy#684]
Hi Squidpy team,

Thanks for creating such a useful tool for the community! I am trying to use it on my CODEX data but having a hard time to plot xy data using sq.pl.spatial_scatter(). Can you help me to:

1. add spatial information or coordinates to the anndata correctly
2. figure out the right `library_id` to use
3. plot `cell_type` using sq.pl.spatial_scatter() evenually

Thank you so much!

Huan Wang
Broad Institute

Here is my code and the error message:

ValueError: Found `library_id: `[array([1346.6675063 ,   78.71032746]), array([1376.0387931 ,   76.88362069])…..array([1216.40237226, 2287.94708029]), array([1268.07407407, 2285.80740741]), array([1435.47701149, 2287.79])] but no `library_key` was specified. Please specify `library_key`.

![Screen Shot 2023-04-26 at 1 17 23 AM](https://user-images.githubusercontent.com/26349803/234477303-3deb47ee-d6eb-4e32-a9c7-a20a92918e9b.png)

**Comment by LLehner** [comment]
Hi @huanlity

thank you for your interest in Squidpy. There will soon be a CODEX reader available, which will make things easier.

Since i encountered different types of CODEX data i'm interested how it is formatted in your case? Is it just a .fcs file containing the table and a .tif file with the images? 

Regarding the `library_id`, have you tried using the column in `.obs`, which contains the annotation for the individual tissue slides/image tiles?

**Comment by LLehner** [comment]
@huanlity 

CODEX formatted files can now also be used with Squidpy, by using [spatialdata-io](https://github.com/scverse/spatialdata-io), which is now used for readers of spatial-omics technologies.

first install latest development version of spatialdata-io:
```pip install git+https://github.com/scverse/spatialdata-io.git@main```

then import spatialdata_io and load the data:

```
import spatialdata_io

sdata = spatialdata_io.codex(path="path/to/directory/")

adata = sdata.table
```
Note: if you don’t use .fcs files but .csv files, set ```fcs=False``` in ```codex()```.

**Comment by huanlity** [comment]
Thank you so much!

Huan
