### ISSUE TITLE
Using squidpy.pl.spatial_segment on Xenium data

### ISSUE THREAD

**Issue by justinesjw** [scverse/squidpy#811]
Hi, 

Thanks for building Squidpy!

May I know how to implement `squidpy.pl.spatial_segment` on Xenium data? I might have missed it, but I could not find it in any tutorial. 

This is the code that I am using 
`sq.pl.spatial_segment(
    adata,
    seg_cell_id="cell_id",
    crop_coord=[(0, 0, 200, 200)]
)`

and I get this error. 
<img width="1139" alt="image" src="https://github.com/scverse/squidpy/assets/26448066/b53d70d6-a94d-4cdc-bd05-8d01905b359f">

I've tried substituting `library_id` with some parameters I can find in the adata, but I can't seem to fix this. 

Thanks!

Best, 
Justine

**Comment by LLehner** [comment]
Hi @justinesjw, thank you for using squidpy.

This method will be deprecated eventually because plotting and visualization of spatial omics data is now done with [spatialdata-plot](https://github.com/scverse/spatialdata-plot) and [napari-spatialdata](https://github.com/scverse/napari-spatialdata). I would recommend using those tools for plotting the segmentation mask on top of spatial omics data.
