### ISSUE TITLE
Sliding window across spatial neighbourhood

### ISSUE THREAD

**Issue by FrancescaDr** [scverse/squidpy#829]
## Description

Implementation of sliding window (inspired by [Kasumi](https://www.biorxiv.org/content/10.1101/2024.03.06.583691v1)) over a spatial neighbourhood or view. 

Input:
- window size
- overlap

Output:
- assignment of cells to sliding window

**Comment by richierip** [comment]
Hi Francesca,

If all you need is a labeling function and not anything fancier I think I can help. I'm a bioinformatics analyst at the KF Cancer Center in Boston - I've done this before in R for a [lung cancer analysis](https://pubmed.ncbi.nlm.nih.gov/38503922/). Wrote up new code that does what you ask and takes in an AnnData object. I haven't tested it that thoroughly so keep that in mind. Two pictures below after running `apply_grid_to_cells(adata, window_size=2500, overlap =500)` on example data from a NanoString CosMx dataset. Since each cell can be in multiple windows when overlap>0, we need multiple columns to keep track of these assignments (up to 25 per cell for these parameters). The output is 25 new columns in `adata` with unique labels for the windows. You can use `pd.melt` to convert `adata.obs` to a long-form dataframe and treat each window's cells as unique, so that later collapsing into window-per-row data is easy. Here's the function:

``` 
import math
import anndata as ad

''' Label cells into "windows" for a coarser spatial analysis 
    If overlap ==0, the windows for a grid and each cell is assigned to one unique window.
    Otherwise, each cell will be assigned to multiple windows. Multiple columns are needed as a result.
    Change  coord_columns to match columns names for XY coordinates in adata.obs '''
def apply_grid_to_cells(adata, window_size = 2500, overlap = 0, coord_columns = ('globalX', 'globalY')):
    x,y = coord_columns
    # No overlap
    if overlap ==0:
        xgrid, ygrid = xgrid, ygrid = (adata.obs[x] - min(adata.obs[x]))// window_size, (adata.obs[y]- min(adata.obs[y])) // window_size
        xrows = xgrid.max()
        adata.obs['Window grid'] = ((ygrid*xrows)+xgrid).astype(int).astype('category')
    else:
        grid_len = math.ceil(window_size / overlap)
        num_grid_systems = grid_len**2
        for i in range(num_grid_systems):
            grid_col_name = f'Sliding window grid {i+1}'
            row, col = (i // grid_len) , (i % grid_len)
            x_grid_start = min(adata.obs[x]) + (overlap * col)
            y_grid_start = min(adata.obs[y]) + (overlap * row)
            xgrid, ygrid = (adata.obs[x] - x_grid_start)// window_size, (adata.obs[y]- y_grid_start) // window_size
            xrows = xgrid.max()
            adata.obs[grid_col_name] = (f'{1+i}_' + ((ygrid*xrows)+xgrid).astype(int).astype(str)).astype('category')
    # adata modified in place

```

![grid_cells_overlap1](https://github.com/scverse/squidpy/assets/35236105/b683a2c4-e711-469f-a047-c1c3043a8469)
![grid_cells_overlap10](https://github.com/scverse/squidpy/assets/35236105/49f6a686-6620-468e-a1d7-d4a2d300c08e)

**Comment by FrancescaDr** [comment]
@richierip thanks for starting this, I will check it out!

To continue the brain storm, some additional implementation features that need to be considered:

- z-coordinate
- storing the sliding windows in `.obs` will explode the storage space. Alternatively storing in `.obsm`
- Move implementation to [SpatialData](https://github.com/scverse/spatialdata-io) instead

Getter functions:
- statistics about min, max, avg number of nodes per window
