### ISSUE TITLE
How to combine the image from ImageCollection object with a anndata object?

### ISSUE THREAD

**Issue by HelloWorldLTY** [scverse/squidpy#897]
Hi, I am a bit confused by the effect of image container. I tried to pass the image in image container (I know the y and x arrays are flipped) to an anndata and plot the spot, but it seems that the direction is always wrong:

```
image = sq.im.ImageContainer(f"../dplfc_data/{idx}_full_image.tif")
image = np.array(image)
spatial_key = "spatial"
library_id = "tissue42"
adata_s.uns[spatial_key] = {library_id: {}}
adata_s.uns[spatial_key][library_id]["images"] = {}
adata_s.uns[spatial_key][library_id]["images"] = {"hires": image}
adata_s.uns[spatial_key][library_id]["scalefactors"] = {
    "tissue_hires_scalef": 1,
    "spot_diameter_fullres": 100,
}

sq.pl.spatial_scatter(adata_s, color="cluster")
```

And the result shows the spot does not match the image:

![Image](https://github.com/user-attachments/assets/16be5e00-cdff-4461-b109-81f3a90a2704)

Do you have any ideas about how to align them? Thanks.

**Comment by HelloWorldLTY** [comment]
I guess the reason is the scaling property (like the spot scaling rate). Is it possible for me to extract such statistics from the spot? Thanks.

**Comment by LLehner** [comment]
Hi @HelloWorldLTY, is this Visium data? I would highly recommend to use the reader provided by [spatialdata-io](https://github.com/scverse/spatialdata-io) which returns you a [spatialdata](https://github.com/scverse/spatialdata) object that contains both anndata table and images. It makes working with spatial omics data much more efficient and you can continue use squidpy functionalities with it. See reader API [here](https://spatialdata.scverse.org/projects/io/en/latest/generated/spatialdata_io.visium.html) and a tutorial on working with spatialdata [here](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/technology_visium.html).

Squidpy also provides a visium reader but that one will be deprecated soon (and is possibly outdated), since all reading is to be done by spatialdata-io.

**Comment by HelloWorldLTY** [comment]
I see, thanks, I think I can try the spatialdata-io.
